"""initial tables

Revision ID: 66a7272103d2
Revises: 
Create Date: 2026-03-02 20:52:18.396012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66a7272103d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('issuing_authority', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('policy_type', sa.String(length=20), nullable=True),
    sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('support_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('application_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('materials_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_park_id', sa.String(length=32), nullable=True),
    sa.Column('is_opc_policy', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('apply_start_date', sa.Date(), nullable=True),
    sa.Column('apply_end_date', sa.Date(), nullable=True),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('apply_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_status'), 'policies', ['status'], unique=False)
    op.create_index(op.f('ix_policies_title'), 'policies', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('policy_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('material_package', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pre_review_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pre_review_type', sa.String(length=10), nullable=True),
    sa.Column('redirect_url', sa.String(length=500), nullable=True),
    sa.Column('redirect_time', sa.DateTime(), nullable=True),
    sa.Column('estimated_review_stage', sa.String(length=20), nullable=True),
    sa.Column('estimated_result_date', sa.DateTime(), nullable=True),
    sa.Column('actual_result', sa.String(length=20), nullable=True),
    sa.Column('actual_result_time', sa.DateTime(), nullable=True),
    sa.Column('result_screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('grant_amount', sa.Float(), nullable=True),
    sa.Column('progress_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_policy_id'), 'applications', ['policy_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('enterprises',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credit_code', sa.String(length=50), nullable=True),
    sa.Column('basic_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('operation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intellectual_property', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_compliance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('general_compliance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opc_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('implicit_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_code')
    )
    op.create_index(op.f('ix_enterprises_user_id'), 'enterprises', ['user_id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('policy_id', sa.String(length=32), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('estimated_amount', sa.Float(), nullable=True),
    sa.Column('gap_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('growth_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collaboration_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_entity_id'), 'match_results', ['entity_id'], unique=False)
    op.create_index(op.f('ix_match_results_policy_id'), 'match_results', ['policy_id'], unique=False)
    op.create_index(op.f('ix_match_results_user_id'), 'match_results', ['user_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('ocr_content', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_entity_id'), 'materials', ['entity_id'], unique=False)
    op.create_index(op.f('ix_materials_user_id'), 'materials', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('msg_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=20), nullable=True),
    sa.Column('related_entity_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('parks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('basic_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('industry_focus', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('investment_needs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opc_community_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parks_user_id'), 'parks', ['user_id'], unique=False)
    op.create_table('talents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id_card_hash', sa.String(length=64), nullable=True),
    sa.Column('basic_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('work_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('professional_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('talent_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('social_insurance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opc_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talents_user_id'), 'talents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_talents_user_id'), table_name='talents')
    op.drop_table('talents')
    op.drop_index(op.f('ix_parks_user_id'), table_name='parks')
    op.drop_table('parks')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_materials_user_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_entity_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_match_results_user_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_policy_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_entity_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_enterprises_user_id'), table_name='enterprises')
    op.drop_table('enterprises')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_policy_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_policies_title'), table_name='policies')
    op.drop_index(op.f('ix_policies_status'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
